/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.sapient.client.gui;

import java.math.BigDecimal;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.swing.JOptionPane;

/**
 *
 * @author spra26
 */
public class EmployeeDetails extends javax.swing.JFrame {
	Connection dbConnection=null;
	PreparedStatement preparedStatement= null;
	ResultSet result = null;
    /**
	 * 
	 */
	private static final long serialVersionUID = -7806016467648312236L;
	/**
     * Creates new form EmployeeDetails
     */
    public EmployeeDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEmployeeID = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblSalary = new javax.swing.JLabel();
        txtEmployeeID = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtSalary = new javax.swing.JTextField();
        btnFindID = new javax.swing.JButton();
        btnInsert = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblEmployeeID.setText("Employee ID");
        lblEmployeeID.setToolTipText("");

        lblFirstName.setText("First Name");

        lblLastName.setText("Last Name");

        lblSalary.setText("Salary");

        txtEmployeeID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployeeIDActionPerformed(evt);
            }
        });

        txtLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastNameActionPerformed(evt);
            }
        });

        btnFindID.setText("Find by ID");
        btnFindID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindIDActionPerformed(evt);
            }
        });

        btnInsert.setText("Add");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        btnUpdate.setText("Modify");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Remove");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnExit)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLastName)
                            .addComponent(lblSalary)
                            .addComponent(lblFirstName)
                            .addComponent(lblEmployeeID))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFirstName)
                            .addComponent(txtSalary)
                            .addComponent(txtLastName)
                            .addComponent(txtEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnFindID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(btnUpdate)
                        .addGap(32, 32, 32)
                        .addComponent(btnDelete)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstName)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLastName)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSalary)
                    .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFindID)
                    .addComponent(btnInsert)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete))
                .addGap(31, 31, 31)
                .addComponent(btnExit)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmployeeIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployeeIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployeeIDActionPerformed

    private void txtLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastNameActionPerformed
    
    private void registerDriver() throws SQLException{
    	DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
    }
    
    private Connection establishConnection() throws SQLException{
    	dbConnection = DriverManager.getConnection("jdbc:oracle:thin:@deltahiti31202:1521:XE","Shivam", "Shivam123456");
    	return dbConnection;
    }
    private void executeFinally(){
    	try {
			if(dbConnection!=null && !dbConnection.isClosed()){
				dbConnection.close();
			}
			if(preparedStatement!=null){
				preparedStatement.close();
			}
			/*if(result!=0){
				result.close();
			}*/
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    }


    
    private void btnFindIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindIDActionPerformed
    	        // TODO add your handling code here:
    	
    	try {
    		registerDriver();
			
			 establishConnection();
			
			/* preparedStatement = dbConnection.prepareStatement("SELECT FIRSTNAME,LASTNAME,SALARY FROM EMP2 WHERE EMPLOYEEID=?");
			
			preparedStatement.setInt(1,Integer.parseInt(txtEmployeeID.getText()));
			
			 result = preparedStatement.executeQuery();
			
			if(result.next()){
				txtFirstName.setText(result.getString(1));
				txtLastName.setText(result.getString(2));
				txtSalary.setText(result.getString(3));
			}
			else{
				JOptionPane.showMessageDialog(this, "No Record Found","Employee ID doesn't Exist",JOptionPane.ERROR_MESSAGE);
			}*/
			 CallableStatement cStatement = null;
				
				cStatement= dbConnection.prepareCall("{Call query_emp(?,?,?,?)");
				int empid= 102;
				
				cStatement.setInt(1,empid);
				
				cStatement.registerOutParameter(2, java.sql.Types.VARCHAR);
				cStatement.registerOutParameter(3, java.sql.Types.DECIMAL);
				cStatement.registerOutParameter(4, java.sql.Types.DECIMAL);
				
				cStatement.execute();
				
				String empName = cStatement.getString(2);
				BigDecimal empSal = cStatement.getBigDecimal(2);
				BigDecimal empComm = cStatement.getBigDecimal(2);
			
			
			
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} finally{
			executeFinally();
			
		}
    	

    }//GEN-LAST:event_btnFindIDActionPerformed
    
    private boolean insertAction(){
    	CallableStatement cStatement = null;
		
		try{cStatement= dbConnection.prepareCall("{Call query_emp(?,?,?,?)");
		int empid= 102;
		
		cStatement.setInt(1,empid);
		
		cStatement.registerOutParameter(2, java.sql.Types.VARCHAR);
		cStatement.registerOutParameter(3, java.sql.Types.DECIMAL);
		cStatement.registerOutParameter(4, java.sql.Types.DECIMAL);
		
		cStatement.execute();
		
		String empName = cStatement.getString(2);
		BigDecimal empSal = cStatement.getBigDecimal(2);
		BigDecimal empComm = cStatement.getBigDecimal(2);
		return true;}
		catch(Exception e){
			return false;
		}
		
    }

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        // TODO add your handling code here:
    	
    	try {
    		registerDriver();
			
			 establishConnection();
			
			 
			 insertAction();
			
			if(result.next()){
				
				JOptionPane.showMessageDialog(this,"EMPLOYEE DETAILS INSERTED");
			}
			else{
				JOptionPane.showMessageDialog(this, "No Record Found","UPDATEDATION FAILED",JOptionPane.ERROR_MESSAGE);
			}
			
			
			
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} finally{
			executeFinally();
		}

    }//GEN-LAST:event_btnInsertActionPerformed
    
    private boolean updateAction(){
    	try{ preparedStatement = dbConnection.prepareStatement("UPDATE EMP2 SET FIRSTNAME=?,LASTNAME=?,SALARY=? WHERE EMPLOYEEID=?");
		 
			
			preparedStatement.setInt(4,Integer.parseInt(txtEmployeeID.getText()));
			preparedStatement.setString(1,txtFirstName.getText());
			preparedStatement.setString(2,txtLastName.getText());
			preparedStatement.setInt(3,Integer.parseInt(txtSalary.getText()));
			
			result=preparedStatement.executeQuery();
			return true;}
    	catch(Exception e){
    		return false;
    	}
    }

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
    	
    	try {
    		registerDriver();
			
			 establishConnection();
			
			
			 updateAction();
			if(result.next()){
				
				JOptionPane.showMessageDialog(this,"EMPLOYEE DETAILS UPDATED");
			}
			else{
				JOptionPane.showMessageDialog(this, "No Record Found","Employee ID doesn't Exist",JOptionPane.ERROR_MESSAGE);
			}
			
			
			
			
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} finally{
			executeFinally();
		}


    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
    	
    	try {
    		registerDriver();
			
			 establishConnection();
			
			 preparedStatement = dbConnection.prepareStatement("DELETE FROM EMP2 WHERE EMPLOYEEID=?");
			 
			
			preparedStatement.setInt(1,Integer.parseInt(txtEmployeeID.getText()));
			
			
			result=preparedStatement.executeQuery();
			
			if(result.next()){
				
				JOptionPane.showMessageDialog(this,"DELETION SUCCESSFUL");
			}
			else{
				JOptionPane.showMessageDialog(this, "No Record Found","Employee ID doesn't Exist",JOptionPane.ERROR_MESSAGE);
			}
			
			
			
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} finally{
			executeFinally();
		}

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
    	//DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());

    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnFindID;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel lblEmployeeID;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblSalary;
    private javax.swing.JTextField txtEmployeeID;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtSalary;
    // End of variables declaration//GEN-END:variables
}
